### ISSUE TITLE
Would you like to share the scene-graph.pkl file?

### ISSUE THREAD

**Issue by chunhuizng** [iacercalixto/butd-image-captioning#1]
Thanks for your code and paper!
I am trying to `create_scene_graph_input_files`. But I can't run `PYTHONPATH="/path/to/graph-rcnn.pytorch" python create_sg_h5.py` successfully, since `graph-rcnn.pytorch`'s `setup.py` can't compile well.

Could you provide these files? 
`train_data_file = 'train_scene-graph.hdf5'`
`    val_data_file = 'val_scene-graph.hdf5'`    
`train_indices_file = 'train_scene-graph_imgid2idx.pkl'`
`val_indices_file = 'val_scene-graph_imgid2idx.pkl'`
`train_ids_file = 'train_scene-graph_ids.pkl'`
`val_ids_file = 'val_scene-graph_ids.pkl'`
Thank you very much!

**Comment by chunhuizng** [comment]
I successfully run `setup.py` in `graph-rcnn.pytorch`, and now the project `butd-image-captioning` on my server can use the `lib` in `graph-rcnn.pytorch`. 
However I still meet one problem: I don't have following two files: `sgg.IMP_pretrained.yaml` and `sg_imp_step_ckpt.pth`. **Could you let me know where I can get both files?** I thought both are important to create scene graph feature.

**Comment by VSJMilewski** [comment]
Hi @aragakiyuiii 
Thank you for your interest in the paper! Unfortunately, I cleaned up my storage and with this deleted all the precomputed feature files, so sharing would not be possible right now. 

Regarding your second question: these are from the graph-rcnn.pytorch repo. Although, we modified the config a bit. You can download the .pth file from [https://github.com/jwyang/graph-rcnn.pytorch#adding-relpn-to-other-methods](https://github.com/jwyang/graph-rcnn.pytorch#adding-relpn-to-other-methods). For the results in the paper we used the one with the RelPN (you might need to change the name of the file or call the argument with the correct filename). 
I pasted a copy of the config below, depending on whether you want to use the RelPN or not, you have to change the `USE_RELPN` flag in the config. 

Let me know if you encounter any other issues. 

```yaml
MODEL:
  ALGORITHM: "sg_imp"
  RELATION_ON: True
  USE_FREQ_PRIOR: False
  USE_RELPN: True
  BACKBONE:
    CONV_BODY: "R-101-C4"
    FREEZE_PARAMETER: True
  RPN:
    FREEZE_PARAMETER: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 151
    FREEZE_PARAMETER: True
  ROI_RELATION_HEAD:
    NUM_CLASSES: 51
    FILTER_NON_OVERLAP: False
    IMP_FEATURE_UPDATE_STEP: 2
    MSDN_FEATURE_UPDATE_STEP: 2
    GRCNN_FEATURE_UPDATE_STEP: 2
    GRCNN_SCORE_UPDATE_STEP: 2
```
